### ISSUE TITLE
Crash in GalacticraftCore InventoryExtended init

### ISSUE THREAD

**Issue by wdh7987** [TeamGalacticraft/Galacticraft#10]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 1.12.2-4.0.2.261

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? SP
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them: More-Planets-1.12.2-2.1.14-CG261 and MorePlanetsExtras-1.12.2-1.0

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: https://pastebin.com/zRVaP6fL

Please provide screenshots / videos / full modlist as needed! 
[Capture](https://user-images.githubusercontent.com/70856103/103047719-617eb880-455a-11eb-8c5d-ab491225b8bc.PNG)

Please state the site that you downloaded Galacticraft from: micdoodle8.com

**Comment by ROMVoid95** [comment]
you have the dev jar versions of the galacticraft mods and micdoodlecore. Please use the non-dev jars

**Comment by wdh7987** [comment]
That fixed the issue. Thank you!
