### ISSUE TITLE
Are there plans to support the forge version? 

### ISSUE THREAD

**Issue by Dr-WeiAL** [TeamGalacticraft/Galacticraft#113]
I was pleasantly surprised when I saw Galacticraft updated to 1.16, but why did it become the fabric version, and what happened?
Or are there any plans to support the forge version in the future? 

(Machine translation, please forgive me if there is a translation error)

**Comment by craftablescience** [comment]
Please read the FAQ channel on the Discord server, at [https://discord.gg/n3QqhMYyFK](https://discord.gg/n3QqhMYyFK)
