### ISSUE TITLE
No Moon Boss Spawning in Moon Dungeon

### ISSUE THREAD

**Issue by TECakaJulian** [TeamGalacticraft/Galacticraft#13]
Im Playing Lapitos Galacticraft and in all of the dungeons i found on the moon (2) there aro no bosses. Thus i can not open the dungeon chest. Some of the Spawner Rooms and Halways are also seperated by walls. Do you need the seed and coordinate of the Moon Base?

**Comment by ROMVoid95** [comment]
this needs to be reported to the owner of Laptios, they are using the 281 build. They need to revert to 280

**Comment by v1993** [comment]
This is a duplicate of #3 and should be closed. As a practical solution, use build 280 (instead of 281) until update arrives.
