### ISSUE TITLE
 in Actions 1.16 mod is fabric? When to update forge?

### ISSUE THREAD

**Issue by chenjj100419** [TeamGalacticraft/Galacticraft#138]
in Actions 1.16 mod is fabric? When to update forge?
high Version forge is done

**Comment by Geolykt** [comment]
wat

**Comment by Seniorendi** [comment]
What do you mean with > high Version forge is done

Here is a quote of the GC FAQ:
> Is Galacticraft being ported to 1.16?
Yes, the main focus of development is rewriting Galacticraft for 1.16! There will be a lot of new and exciting features, some of which are either added already or are a work in progress. Using the Architectury API, we will be able to produce a mod JAR that will work with both the Forge and Fabric modloaders. We are currently focusing development on Fabric, but once Architectury is implemented and development on the Forge side speeds up, it is planned to be the next major version of Galacticraft, GC5.
