### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by CMSEv7** [TeamGalacticraft/Galacticraft#141]
I want to translate Galacticraft to French. I know þere is a translated bit, but I want to translate þe oþer bit and correct þe translations.
Je voudrais traduire Galacticraft en français. Je sais qu'il y a une partie déjà traduite, mais j'aimerais traduire l'autre partie et corriger les traductions.

I speak þe two languages !
Je parle les deux langues !

**Comment by vos6434** [comment]
Submit a pull request with your updated translations.

**Comment by CMSEv7** [comment]
Done.
