### ISSUE TITLE
Game crashed when right-clicking a fluid pipe corner with a greate

### ISSUE THREAD

**Issue by Casmin7** [TeamGalacticraft/Galacticraft#146]
## Game
Galacticraft version: #144 
<br/>Game Logs ([gist](https://gist.github.com)): 
[crash-2021-07-22_21.17.33-client.txt](https://github.com/TeamGalacticraft/Galacticraft/files/6864471/crash-2021-07-22_21.17.33-client.txt)

<br/>Multiplayer? (Yes, No, LAN): No

## Screenshots: Im sorry I dodn't think it would crash

**Comment by JoeZwet** [comment]
reproduced, full log attached.
[latest.log](https://github.com/TeamGalacticraft/Galacticraft/files/6865154/latest.log)
