### ISSUE TITLE
 I picked the moon and dropped the client

### ISSUE THREAD

**Issue by vajdom** [TeamGalacticraft/Galacticraft#193]
### Mod Loader

Forge (NYI)

### Version Information

4.0.20.280

### Log or Crash Report

---- Minecraft Crash Report ----  WARNING: coremods are present:   WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)   Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)   llibrary (llibrary-core-1.0.11-1.12.2.jar)   wings (wings-1.1.6-1.12.2.jar)   MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)   TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)   TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)   SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)   CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar) Contact their authors BEFORE contacting forge  // Hey, that tickles! Hehehe!  Time: 11/5/21 6:07 PM Description: Ticking player  java.lang.NullPointerException: Ticking player 	at asmodeuscore.core.event.AsmodeusEvent.doPressureForEntity(AsmodeusEvent.java:209) 	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:154) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_476_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581) 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095) 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) 	at java.lang.Thread.run(Thread.java:745)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Server thread Stacktrace: 	at asmodeuscore.core.event.AsmodeusEvent.doPressureForEntity(AsmodeusEvent.java:209) 	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:154) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_476_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581) 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095) 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)  -- Player being ticked -- Details: 	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP) 	Entity ID: 734 	Entity Name: Vajdom 	Entity's Exact location: -247.50, 900.00, -1907.50 	Entity's Block location: World: (-248,900,-1908), Chunk: (at 8,56,12 in -16,-120; contains blocks -256,0,-1920 to -241,255,-1905), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537) 	Entity's Momentum: 0.00, -0.07, 0.00 	Entity's Passengers: [] 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null Stacktrace: 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)  -- Ticking connection -- Details: 	Connection: net.minecraft.network.NetworkManager@3b9930b4 Stacktrace: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) 	at java.lang.Thread.run(Thread.java:745)  -- System Details -- Details: 	Minecraft Version: 1.12.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 13467066448 bytes (12843 MB) / 15367929856 bytes (14656 MB) up to 16844324864 bytes (16064 MB) 	JVM Flags: 8 total; -Xmn128M -Xmx16047M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95 	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 66 mods loaded, 65 mods active 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored  	| State  | ID                         | Version              | Source                                        | Signature                                | 	|:------ |:-------------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- | 	| LCHIJA | minecraft                  | 1.12.2               | minecraft.jar                                 | None                                     | 	| LCHIJA | mcp                        | 9.42                 | minecraft.jar                                 | None                                     | 	| LCHIJA | FML                        | 8.0.99.99            | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 | 	| LCHIJA | forge                      | 14.23.5.2855         | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 | 	| LCHIJA | micdoodlecore              |                      | minecraft.jar                                 | None                                     | 	| LCHIJA | voxelmap                   | 1.9.25               | forgemod_VoxelMap-1.9.28_for_1.12.2.jar       | None                                     | 	| LCHIJA | quarryplus                 | 12.5.5               | AdditionalEnchantedMiner-1.12.2-12.5.5.jar    | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 | 	| LCHIJA | quarryplus_ct              | 12.5.5               | AdditionalEnchantedMiner-1.12.2-12.5.5.jar    | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 | 	| LCHIJA | mantle                     | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                      | None                                     | 	| LCHIJA | jei                        | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar                     | None                                     | 	| LCHIJA | ctm                        | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     | 	| LCHIJA | baubles                    | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     | 	| LCHIJA | thaumcraft                 | 6.1.BETA26           | Thaumcraft-Mod-1.12.2.jar                     | None                                     | 	| LCHIJA | twilightforest             | 3.11.1021            | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     | 	| LCHIJA | tconstruct                 | 1.12.2-2.13.0.183    | TConstruct-1.12.2-2.13.0.183.jar              | None                                     | 	| LCHIJA | galacticraftcore           | 4.0.2.280            | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     | 	| LCHIJA | galacticraftplanets        | 4.0.2.280            | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     | 	| LCHIJA | asmodeuscore               | 0.0.27               | AsmodeusCore-1.12.2-0.0.27.jar                | None                                     | 	| LCHIJA | autoreglib                 | 1.3-32               | AutoRegLib-1.3-32.jar                         | None                                     | 	| LCHIJA | backpack                   | 3.0.2                | backpack-3.0.2-1.12.2.jar                     | None                                     | 	| LCHIJA | bettermineshafts           | 1.12.2-2.2.1         | BetterMineshaftsForge-1.12.2-2.2.1.jar        | None                                     | 	| LCHIJA | bibliocraft                | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     | 	| LCHIJA | buildcraftlib              | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcraftcore             | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcraftbuilders         | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcrafttransport        | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcraftsilicon          | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcraftcompat           | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcraftenergy           | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcraftfactory          | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | buildcraftrobotics         | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     | 	| LCHIJA | chesttransporter           | 2.8.8                | ChestTransporter-1.12.2-2.8.8.jar             | None                                     | 	| LCHIJA | codechickenlib             | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 | 	| LCHIJA | chickenchunks              | 2.4.2.74             | ChickenChunks-1.12.2-2.4.2.74-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 | 	| LCHIJA | clumps                     | 3.1.2                | Clumps-3.1.2.jar                              | None                                     | 	| LCHIJA | conarm                     | 1.2.5.10             | conarm-1.12.2-1.2.5.10.jar                    | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 | 	| LCHIJA | doggytalents               | 1.15.1.6             | DoggyTalents-1.12.2-1.15.1.6.jar              | None                                     | 	| LCHIJA | orelib                     | 3.6.0.1              | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a | 	| LCHIJA | dsurround                  | @VERSION@            | DynamicSurroundings-1.12.2-3.6.3.jar          | None                                     | 	| LCHIJA | mjrlegendslib              | 1.12.2-1.2.1         | MJRLegendsLib-1.12.2.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 | 	| LCHIJA | extraplanets               | 1.12.2-0.7.3         | Extra-Planets-Mod-1.12.2.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 | 	| LCHIJA | llibrary                   | 1.7.20               | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec | 	| LCHIJA | fossil                     | 8.0.5                | fossilsarcheology-8.0.5.jar                   | None                                     | 	| LCHIJA | gravestone                 | 1.0.12               | Gravestone-Mod-1.12.jar                       | None                                     | 	| LCHIJA | waila                      | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     | 	| LCHIJA | iceandfire                 | 1.9.0                | iceandfire-1.9.0.jar                          | None                                     | 	| LCHIJA | inventorytweaks            | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe | 	| LCHIJA | ironchest                  | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar               | None                                     | 	| LCHIJA | stevekung's_lib            | 1.1.10               | SteveKunG's-Lib-1.12.2-1.1.10.jar             | None                                     | 	| LCHIJA | moreplanets                | 2.2.1                | More-Planets-Mod-1.12.2.jar                   | None                                     | 	| LCHIJA | mowziesmobs                | 1.5.8                | mowziesmobs-1.5.8.jar                         | None                                     | 	| LCHIJA | naturescompass             | 1.8.5                | NaturesCompass-1.12.2-1.8.5.jar               | None                                     | 	| LCHIJA | patchouli                  | 1.0-23.6             | Patchouli-1.0-23.6.jar                        | None                                     | 	| LCHIJA | roguelike                  | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     | 	| LCHIJA | spaceambient               | 0.0.1                | SpaceAmbient-1.12.2-0.0.1.jar                 | None                                     | 	| LCHIJA | thaumicperiphery           | 0.3.1                | Thaumic-Periphery-Mod-1.12.2.jar              | None                                     | 	| LCHIJA | thaumictinkerer            | 1.12.2-5.0-620a0c5   | Thaumic-Tinkerer-Mod-1.12.2.jar               | None                                     | 	| LCHIJA | thaumicjei                 | 1.6.0                | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     | 	| LCHIJA | tlauncher_custom_cape_skin | 1.4                  | tlskincape1.12.2-1.4.jar                      | None                                     | 	| LCHIJA | treechoppin                | 1.0.0                | Tree-Chopper-Mod-1.12.2.jar                   | None                                     | 	| LCHIJA | wings                      | 1.1.6                | wings-1.1.6-1.12.2.jar                        | None                                     | 	| LCHIJA | mowzies_wings              | 1.0.0                | wings-1.1.6-1.12.2.jar                        | None                                     | 	| LCHIJA | bauble_wings               | 1.0.0                | wings-1.1.6-1.12.2.jar                        | None                                     | 	| LCHIJA | wolfarmor                  | 3.7.5                | wolfarmor-1.12.2-3.7.5-universal-signed.jar   | e94e38a605842477f3ec218e6fcf781f6b3f7f89 | 	| LCHIJA | worldedit                  | 6.1.10               | worldedit-forge-mc1.12.2-6.1.10-dist.jar      | None                                     | 	| UD     | mobends_wings              | 1.0.0                | wings-1.1.6-1.12.2.jar                        | None                                     |  	Loaded coremods (and transformers):  WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)    Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)   invtweaks.forge.asm.ContainerTransformer llibrary (llibrary-core-1.0.11-1.12.2.jar)   net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer   net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher wings (wings-1.1.6-1.12.2.jar)   me.paulf.wings.server.asm.WingsRuntimePatcher   me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)   micdoodle8.mods.miccore.MicdoodleTransformer TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)   gloomyfolken.hooklib.minecraft.PrimaryClassTransformer TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)    SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)    CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)   team.chisel.ctm.client.asm.CTMTransformer 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread. 	Pulsar/tconstruct loaded Pulses:  		- TinkerCommons (Enabled/Forced) 		- TinkerWorld (Enabled/Not Forced) 		- TinkerTools (Enabled/Not Forced) 		- TinkerHarvestTools (Enabled/Forced) 		- TinkerMeleeWeapons (Enabled/Forced) 		- TinkerRangedWeapons (Enabled/Forced) 		- TinkerModifiers (Enabled/Forced) 		- TinkerSmeltery (Enabled/Not Forced) 		- TinkerGadgets (Enabled/Not Forced) 		- TinkerOredict (Enabled/Forced) 		- TinkerIntegration (Enabled/Forced) 		- TinkerFluids (Enabled/Forced) 		- TinkerMaterials (Enabled/Forced) 		- TinkerModelRegister (Enabled/Forced) 		- wailaIntegration (Enabled/Not Forced)  	Patchouli open book context: n/a 	Profiler Position: N/A (disabled) 	Player Count: 1 / 8; [GCEntityPlayerMP['Vajdom'/734, l='Vajdom', x=-247.50, y=900.00, z=-1907.50]] 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'fml,forge' 	OptiFine Version: OptiFine_1.12.2_HD_U_G5 	OptiFine Build: 20210124-142939 	Render Distance Chunks: 12 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: null 	OpenGlVersion: 4.5.0 - Build 23.20.16.5018 	OpenGlRenderer: Intel(R) UHD Graphics 630 	OpenGlVendor: Intel 	CpuCount: 8

### Reproduction steps

1. Lunch on the earth
2. I picked a month
3. minecraft crash

**Comment by craftablescience** [comment]
Incorrect repository, and please ask this question on the [Galacticraft community Discord](https://discord.gg/bSZR3bdRW8) instead of making an issue.

**Comment by Seniorendi** [comment]
Oh no he dropped the client
poor client
