### ISSUE TITLE
Crash after launching a rocket.

### ISSUE THREAD

**Issue by appollon41** [TeamGalacticraft/Galacticraft#2]
Minecraft version: 1.12.2, forge 2.6.2.83
Galacticraft version ("latest" is not a valid option):
GalacticraftCore-1.12.2-4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
MP server, with no plugin architecture involved.

Any Galacticraft add-ons installed? Please list all of them:
Yes. GC Planets 1.12.2-4.0.2.280, PlanetProgression-1.12.2-0.4.5

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
4 crashes, each one was at the end of a rocket travel
https://pastebin.com/Ci5Fs9gE
https://pastebin.com/2ueKpJtx
https://pastebin.com/Q79Bd0mX
https://pastebin.com/5KnqJ7Ph
https://pastebin.com/bMM56k7N (last logs before crashing, those lines appear each time before the server shuts off. There is nothing after, excepted for the: "A server tick took 90.0 s" etc.. and nothing before than normal logs)
You can ask me for full logs if you need it.

Please provide screenshots / videos / full modlist as needed
Tell me if full mod list is needed, but this is a big modpack, based on a stable one. 
idk if that might help, but I have Advanced Rocketry installed too, but it doesn't seem to be a problem.
I have Flan's mod too, and it appears in the crash logs.

Please state the site that you downloaded Galacticraft from:
The official one.

Hello. So I'm having some issues that happen every time I try to change dimension by taking a rocket. As soon as I must arrive to the solar system map, the server freezes until it crashes. It happened several times, each time I or my friend tried to access to another planet. The first bizarre thing is that I did create a space station, and I created it by launching myself in a rocket, and everything went alright. Satellite rocket launches went fine too. 
The second weird event is that each crash log is not involving the same problems, excepted for galacticraft dimensions load and flan's mod as I can see. (I did declare an issue on flan's github)

Thanks a lot for helping me.

**Comment by appollon41** [comment]
Any idea?

**Comment by ROMVoid95** [comment]
There is a option in your server.properties file `max-tick-time`, you can either increase the number to allow longer duriations of ticks allowed before the server shuts itself down (which is what is happening in the logs provided) or you can completely disable it by giving it a value of `-1`.

It could be just having the mods seen requires a tad more time to load dimensions than normal. Or a mod could be causing the server to hang, increasing or disabling the watchdog might give you more info. You could also, try reducing the amount of RAM your giving the server,  depending on the number of active players isn't high. As giving too much RAM to Java could cause adverse affects such as this.

**Comment by appollon41** [comment]
It's weird. When I take out flan's mod, it takes about 2 or 3 seconds to access the /dimensiontp tab, it seems weird to let the server wait for more than 90 s for it to compute, but I'll try that. 
I can't reduce allowed RAM btw, I ain't on a dedicated server I own but on an online hosting, which is powerful and great, but I can't change RAM on it. I'll try my best and figure it out.

**Comment by appollon41** [comment]
Solved by updating stable Flan's version with the latest beta version.
