### ISSUE TITLE
A fatal error has occurred, the connection is terminated

### ISSUE THREAD

**Issue by Topnitel** [TeamGalacticraft/Galacticraft#21]
Two of my friends tried going to the moon in my server with the Galacticraft mod and many other add-ons, they got timed out right before going out of the atmosphere, and when they rejoin the error in the title occurs. Now they are stuck in outer space, unable to join
Here is a log consisting of just one of them joining and disconnecting https://mclo.gs/CyksIoO (yes Aternos because dad doesn't let me pay)
Update: I am stuck too ;-;![image](https://user-images.githubusercontent.com/74977660/111024239-dcc76c00-83dd-11eb-8927-be78e8a11992.jpeg)
Another update: it only seems to happen in this server

**Comment by Topnitel** [comment]
update i am stuck too
the galaxy map pops up for one second and then ![image](https://user-images.githubusercontent.com/74977660/111024166-7fcbb600-83dd-11eb-97b6-6c8f95ea97f7.jpeg)

**Comment by Topnitel** [comment]
good news! after digging into my client logs it was an issue caused by the galaxyspace addon where i forgot to disable the enableNewGalaxyMap option

**Comment by arkinetic** [comment]
tysm i was looking for this, i thought i replaced all the configs but apparently the thing in asmodeuscore didnt save to false. when i opened the config on the aternos server it said enableNewGalaxyMap=true
