### ISSUE TITLE
Gradle fails to get GalaticraftEngery and GalaticraftAPI

### ISSUE THREAD

**Issue by Derailedzack** [TeamGalacticraft/Galacticraft#210]
### Mod Loader

Fabric

### Version Information

main

### Log or Crash Report

https://scans.gradle.com/s/yo52ghwnia2bu

### Reproduction steps

1. Run gradlew
2. Observe A build failure

**Comment by ROMVoid95** [comment]
@Derailedzack the domain hosting our maven repository is down at this time.

**Comment by Derailedzack** [comment]
Oh

**Comment by molehauling** [comment]
That's real fun stuff, gives me an idea though.

**Comment by LawOfSynergy** [comment]
Why was this ticket closed if the maven repo is still down?

**Comment by ROMVoid95** [comment]
The author himself closed it.

**Comment by ROMVoid95** [comment]
@LawOfSynergy @Derailedzack @molehauling 

Ive setup a temporary maven until the main site is backup and running

on line 99 in `build.gradle.kts` 
change
```
	maven("https://maven.galacticraft.dev") {
```
to 
```
	maven("https://maven.galacticraft.net/releases") {
```

**Comment by LawOfSynergy** [comment]
Awesome! I'll try to get a successful build going tonight then.

**Comment by PyrrhaDevs** [comment]
the `maven.galacticraft.dev` repo is back online. closing.
