### ISSUE TITLE
AccessWidener causes crash

### ISSUE THREAD

**Issue by glowiak** [TeamGalacticraft/Galacticraft#224]
### Mod Loader

Fabric

### Version Information

main

### Log or Crash Report

https://gist.github.com/glowiak/ead8d442f5f0424ea30696fddfff0d52

### Reproduction steps

Build latest versions of GC* (remove the license check in build.gradle.kts, it causes fail), in PolyMC/multimc create 1.17.1 fabric instance, add built jars, libblockattributes architectury and fabric api. try to launch

**Comment by marcus8448** [comment]
You cannot use dev jars in a production environment. Use the normal jars (the ones without any suffix) that are built.

**Comment by glowiak** [comment]
Oh, ok

**Comment by glowiak** [comment]
https://github.com/TeamGalacticraft/Galacticraft/issues/225
