### ISSUE TITLE
No such method error mojang serialization codec

### ISSUE THREAD

**Issue by glowiak** [TeamGalacticraft/Galacticraft#225]
### Mod Loader

Fabric

### Version Information

main

### Log or Crash Report

https://gist.github.com/glowiak/a33b5b7929bf4ebf105515c8529bdd0c

### Reproduction steps

Build latest versions of GC* (remove the license check in build.gradle.kts, it causes fail), in PolyMC/multimc create 1.17.1 fabric instance, add built jars, libblockattributes architectury and fabric api. try to launch

**Comment by marcus8448** [comment]
You are using 1.18-pre1 Galacicraft API with 1.17 Galacicraft.
In the future, please don't ask for tech/launching support for Galacticraft on this issue tracker (use discussions or discord instead). Galacticraft 5 is still in pre-alpha and therefore we do not recommend or support using it outside of the development of the mod.
