### ISSUE TITLE
Incompatibility with Vic's Modern Warfare 2.0

### ISSUE THREAD

**Issue by ScrPotato** [TeamGalacticraft/Galacticraft#25]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:1.12.2
Galacticraft version ("latest" is not a valid option):
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
MicdoodleCore-1.12.2-4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
Single player

Any Galacticraft add-ons installed? Please list all of them:
None

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
No Crashes

Please provide screenshots / videos / full modlist as needed
Mod List:
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
MicdoodleCore-1.12.2-4.0.2.280
mw_2.0-0.4.4.6_mc1.12.2

Please state the site that you downloaded Galacticraft from:
https://micdoodle8.com/mods/galacticraft/downloads

This probably happens because of Galacticraft using a custom player model. 

Screenshots:
![1](https://user-images.githubusercontent.com/36772485/112137430-47985480-8be1-11eb-9581-c689c4cbea23.png)
item is not where it should be

![2](https://user-images.githubusercontent.com/36772485/112137447-5121bc80-8be1-11eb-90c7-440b86b73560.png)
same with thermal armor (and oxygen mask too)

![3](https://user-images.githubusercontent.com/36772485/112137502-65fe5000-8be1-11eb-83ee-85021cb8de6a.png)
we can see that its in its right place IF you were standing

![4](https://user-images.githubusercontent.com/36772485/112137554-744c6c00-8be1-11eb-900a-28df90e4fd27.png)
Crouching is broken too

NOTE: You need to set allowEmmisiveItems=false in forge.cfg in order to use vic's modern warfare.

EDIT: The hitbox DOES change

**Comment by ROMVoid95** [comment]
Both Galacticraft & Vic's Modern Warfare Mod change the Player and Player rendering. Didn't look too promising when seeing it also doesn't run on a certain Forge version (very old version) unless 1 of 3 solutions is done, as  well as being a closed source mod it pretty much puts it on the level of Optifine when it comes to compatibility. Closing this as `Will Not Fix`.

**Comment by ScrPotato** [comment]
Maybe mention it on https://wiki.micdoodle8.com/wiki/Compatibility ?
