### ISSUE TITLE
[1.7.10] Microgravity in Asteroids Not Engaging

### ISSUE THREAD

**Issue by Temmie19** [TeamGalacticraft/Galacticraft#28]
Minecraft version: 1.7.10 Forge 10.13.4.1614 
Galacticraft version: 1.7-3.0.12.504

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
Singleplayer

Expected behavior: Very slowly floating down in a free fall when in asteroid dimension
Actual behavior: [https://youtu.be/pj2gdttG3lU](url)

Please state the site that you downloaded Galacticraft from:
Micdoodle's website

I recognize this likely won't be fixed, but I figured I might as well report it.

**Comment by craftablescience** [comment]
Please post the mods that you have installed, if any

**Comment by ROMVoid95** [comment]
Appreciate the report anyway, may prove useful to others on searching issues. 
Going to close since 1.7.x is no longer supported.
