### ISSUE TITLE
Connect Pressurized Tube(in mek) with Sealable Fluid Pipe will crash the server

### ISSUE THREAD

**Issue by quqi2** [TeamGalacticraft/Galacticraft#281]
### Mod Loader

Forge (NYI)

### Version Information

Galacticraft-1.12.2-4.0.2.284

### Log or Crash Report

https://gist.github.com/quqi2/71a6ee7ecafd52f0e492a571b83f948a

### Reproduction steps

1. Connect a Pressurized Tube(in mek) with Sealable Fluid Pipe
2. Crash!
(I have tried to restart the server, but it cannot be start until I have deleted the world)

**Comment by quqi2** [comment]
Connect Pressurized Tube(in mek) with Fluid Pipe will also cause this problem

**Comment by TheMCSpacePro** [comment]
This GitHub is for Galacticraft 5, not Galacticraft 4 (version number says you're on GC4). You want this one: [https://github.com/TeamGalacticraft/Galacticraft-Legacy](url)

Also, that isn't even the LATEST version of Galacticraft 4. Pretty sure that issue's been fixed in newer versions.
