### ISSUE TITLE
Cannot go onto the moon using celestial menu

### ISSUE THREAD

**Issue by sheazywi** [TeamGalacticraft/Galacticraft#297]
### Mod Loader

Fabric

### Version Information

c6eef0e

### Log or Crash Report

Didn't crash

### Reproduction steps

1. Go onto the celestial menu using the command
2. Click onto the earth
3. Then go on the moon
4. Click teleport
5. Put this happens.
![image](https://github.com/TeamGalacticraft/Galacticraft/assets/73042839/ed0baba5-6110-4471-aa3c-d4afdb4200e0)
6. When clicking to Back to server list it forces us to get out of the world and put us into the server list 
<img width="961" alt="image" src="https://github.com/TeamGalacticraft/Galacticraft/assets/73042839/0b9432ca-f7bb-4601-9e68-d61094cf41a7">

**Comment by AlphaMode** [comment]
Fixed in [a555a0e](https://github.com/TeamGalacticraft/Galacticraft/commit/a555a0e850c45f2b6462f76511c7791dbe2498b8)
