### ISSUE TITLE
Moon dungeon Worldgen glitch & No boss in Boss room

### ISSUE THREAD

**Issue by domenic77x** [TeamGalacticraft/Galacticraft#3]
Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option):  GalacticraftCore-1.12.2-4.0.2.281

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
Multiplayer (MP) w/ forge-1.12.2-14.23.5.2854.jar

Any Galacticraft add-ons installed? Please list all of them:
Galacticraft-Planets-1.12.2-4.0.2.281
MicdoodleCore-1.12.2-4.0.2.281

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site:
logs_debug.log
https://www.dropbox.com/s/g4a72c58n5e44gl/logs_debug.log?dl=0

server log report
https://pastebin.com/PxLycHRT

Please provide screenshots / videos / full modlist as needed
https://imgur.com/a/gxoqwP9

https://imgur.com/a/GMJtqJN

Please state the site that you downloaded Galacticraft from:
https://micdoodle8.com/mods/galacticraft/downloads

As my friend and I explored the moon for dungeons we came across a worldgen issue in which the dungeons tunnels are not connected correctly. Tunnel doors are blocked by the bricks in the place it should be open. This problem we easily passed by just mining through until the next tunnel. The next thing we noticed is no boss spawned in the boss room. We then /summon'd a boss because we were pretty disappointed. Also to note, in the 2/2 dungeon we found, the boss did not spawn as well as the treasure room being open and blocked by the bricks. Coords for the dungeon can be found in the posted imgur screenshot.

**Comment by craftablescience** [comment]
I'm not sure how to fix this yet, but this appears to be a problem:

`[23:25:15] [Server thread/WARN] [FML]: Galacticraft Core loaded a new chunk [-140, 96] in dimension -28 (moon.moon) while populating chunk [-142, 96], causing cascading worldgen lag.`

**Comment by domenic77x** [comment]
Tested out this problem in SP and the same thing occurs. Tunnels are blocked and not generating the doors correctly. As well as the boss not generating in the boss room and treasure room being open. On top of this world gen problem, there seems to be loot spewed all over the floor of the dungeon ontop. There is still loot in the chest but loot on the floor as well. Screenshots posted below
https://imgur.com/a/ts8HDgC

**Comment by BlesseNtumble** [comment]
https://github.com/micdoodle8/Galacticraft/pull/4053
Already fixed, wait new build.

**Comment by domenic77x** [comment]
> [micdoodle8#4053](https://github.com/micdoodle8/Galacticraft/pull/4053)
> Already fixed, wait new build.

That issue was specifically SpongeForge, will this also fix regular forge. I'm running a server without SpongeForge.

**Comment by marcus8448** [comment]
Fixed by f9af2c00afa33646eebedb1fc2de8943a33a1e73. My fault - I forgot to test the boss rooms. Dungeons on SpongeForge will be broken, while I look for a real fix.

**Comment by SonicSpeedster16** [comment]
I too am running into this issue using Galacticraft 4.0.2.281. Is a new build to fix this planned or should I go back to using build 280 for now?

**Comment by xJon** [comment]
Is there any ETA for this fix to be publicly released?

**Comment by MJRLegends** [comment]
Keep using build 280 for now

**Comment by Enterprise12nx01** [comment]
From my understanding, we should use version 280 as otherwise bosses dont spawn but dungeons dont generate correctly? is this in both versions?
ty

**Comment by v1993** [comment]
@Enterprise12nx01 From my understanding, 280 works in most cases (both bosses and dungeons function), while 281 breaks these everywhere but fixes them for Sponge users. So yep, you should stick to 280 until update is released (unless you use Sponge).
