### ISSUE TITLE
Earth moving on Moon

### ISSUE THREAD

**Issue by sheazywi** [TeamGalacticraft/Galacticraft#300]
### Mod Loader

Fabric

### Version Information

6cbf369

### Log or Crash Report

Didn't crash

### Reproduction steps

1. Go on the moon using the command
2. Start moving on the z axis
3. And the earth is moving like you
You will need to move very fast like very fast to notice it. Used DaFlight.
Bug shown on video, had to put it on youtube because of it enormous size.
https://youtu.be/ZFZMv1sXhys

**Comment by sheazywi** [comment]
Forgot to mention that the "issue" or bug is situated in MoonSkyRenderer.java in render/dimension line 150
<img width="506" alt="image" src="https://github.com/TeamGalacticraft/Galacticraft/assets/73042839/b86aa879-ceec-40c6-acb4-e99ca79fe9b5">

**Comment by sheazywi** [comment]
Realized that this is a actual feature in the original mod.

**Comment by EzerArch** [comment]
> Realized that this is a actual feature in the original mod.
Yes. The Earth moves relatively to Moon's equator (so to speak).

There were eclipses too: https://www.youtube.com/watch?v=NAmqd__yzbo
