### ISSUE TITLE
crash when placing oxygen storage module

### ISSUE THREAD

**Issue by sheazywi** [TeamGalacticraft/Galacticraft#308]
### Mod Loader

Fabric

### Version Information

059d16c

### Log or Crash Report

https://gist.github.com/sheazywi/c3c4eb82d2ebd3d2399cd7dddbbc7355

### Reproduction steps

found when using feature/wires-v4 (059d16c)
bug doesn't happen when using latest main commit (b618b75)
1.Generate a world
2.Place the Oxygen Storage Module
3.Game freeze and crashes after a matter of seconds

**Comment by marcus8448** [comment]
Thanks for the bug report!

**Comment by sheazywi** [comment]
np
