### ISSUE TITLE
Add Oxygen Gear for Pets

### ISSUE THREAD

**Issue by vos6434** [TeamGalacticraft/Galacticraft#33]
shift right-click to equip oxygen gear for a pet.
shift right-click on the pet again to see the remaining oxygen.

- [ ] Parrot
- [ ] Wolf
- [ ] Cat

**Comment by Atakku** [comment]
- [ ] Horses
- [ ] Donkeys
- [ ] Mules
- [ ] Llamas
- [ ] Foxes

**Comment by EzerArch** [comment]
Ok, but do we have rockets that transport animals?

**Comment by Atakku** [comment]
~~Just yank the pet to the rocket using a leash and call it a day~~

**Comment by CheetahCyberBoi** [comment]
Maybe only allow light O2 tanks for it because bigger ones would just be cruel.

**Comment by ChaosDogG** [comment]
@Atakku on ur pet list additions, FOXES CANNOT BE TAMED! The fox is unable to be tamed, only gain its trust which the game treats as separate instances. You cannot make a fox sit, nor can you use it for transport, ergo it is not tamable. The breeding method only results in the offspring fully trusting the player who bred the parents, which as I'll say again, the game treats differently in comparison to a tamed mob.

**Comment by ChaosDogG** [comment]
Ik this sounds harsh, but ive seen SO many ppl get mixed up in thinking foxes r tamable when they're not...

**Comment by Atakku** [comment]
> Ik this sounds harsh, but ive seen SO many ppl get mixed up in thinking foxes r tamable when they're not...

Yeah I didn't know foxes weren't tamable untill a couple weeks ago
