### ISSUE TITLE
CODE : 443 [maven.galacticraft.net] - could not download files!

### ISSUE THREAD

**Issue by ErythroCraft** [TeamGalacticraft/Galacticraft#343]
### Mod Loader

Fabric

### Version Information

1.20.1

### Log or Crash Report

https://gist.github.com/ErythroCraft/b37cd0c041ecd11c1a6b1a51ab26caf8

### Reproduction steps

1. Start compiling test build
2. Crash!

Same as:
https://github.com/TeamGalacticraft/Galacticraft/actions/runs/9885925771

**Comment by TheMCSpacePro** [comment]
I think the maven is currently down. One of the team members is presently trying to fix it.

**Comment by marcus8448** [comment]
We've migrated to an alternative maven - builds should be working once again.
