### ISSUE TITLE
My build keeps failing.

### ISSUE THREAD

**Issue by syzygy2896** [TeamGalacticraft/Galacticraft#347]
### Mod Loader

Fabric

### Version Information

main

### Log or Crash Report

Report is on the image

### Reproduction steps

My build keeps failing upon compiling saying "could not download maven mojarn files" SSL missconfiguration.

![Screenshot 2024-08-22 125255](https://github.com/user-attachments/assets/0a0cd2c6-aa2b-4d27-910b-c0893c7f2239)

**Comment by mMONTAGEe** [comment]
galacticraft maven is down currently
![image](https://github.com/user-attachments/assets/b371aeeb-f03a-4951-8b30-d3c5ab80a099)

**Comment by marcus8448** [comment]
We've migrated to an alternative maven - builds should be working once again.
