### ISSUE TITLE
Villagers and wandering traders model is broken

### ISSUE THREAD

**Issue by Stablelly** [TeamGalacticraft/Galacticraft#370]
### Version Information

v5.0.0-prealpha+298

### Log or Crash Report

Nope

### Reproduction steps

See image
![2024-11-25_00 26 24](https://github.com/user-attachments/assets/4d57f0d8-2d98-495d-b08c-dbfd96a4b58e)
![2024-11-25_00 28 32](https://github.com/user-attachments/assets/57b97193-1d09-4432-9bee-aa3fa03209fc)

**Comment by TheMCSpacePro** [comment]
I would assume the log should tell us why, uh, THAT'S happening.
