### ISSUE TITLE
[BUG]crash on spawning a heavy sealable wire

### ISSUE THREAD

**Issue by lingyun-create** [TeamGalacticraft/Galacticraft#371]
### Version Information

mian 1.21.1

### Reproduction steps

1 spawn a heavy sealable wire
2 ...
3 crash

and I make texture for it
![IMG_20241208_010411](https://github.com/user-attachments/assets/3a613aa7-d583-4729-be17-dfe6f60aaca3)
hope it can be helpful

**Comment by TheMCSpacePro** [comment]
Is there a crash log you can provide?
