### ISSUE TITLE
[QUESTION] Custom Space Station?

### ISSUE THREAD

**Issue by SonicSpeedster16** [TeamGalacticraft/Galacticraft#8]
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Galacticraft version ("latest" is not a valid option): 4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? Potentially all

Any Galacticraft add-ons installed? Please list all of them: GalaxySpace, Galacticraft Tweaker

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: N/A

Please state the site that you downloaded Galacticraft from: https://www.micdoodle8.com/mods/galacticraft/downloads

Hello, my apologies if this is not the correct place to ask questions, but I've been unable to find an answer elsewhere.

I am currently building a modpack that is largely centered around Galacticraft. My intention is to have the Overworld be a largely inhospitable place with an early game goal of setting up a space station and having that be the player's primary base of operations for the remainder of the pack. However, to better incentivize moving to the space station I'd like to create a larger, custom station that the player will go to on their initial visit. Is this possible?

**Comment by MJRLegends** [comment]
also https://forum.micdoodle8.com/index.php would be a better place to ask this

**Comment by SonicSpeedster16** [comment]
Thank you for the confirmation that a new custom mod will be needed and for the forum link. Not sure how I missed the forums before.
